<a href="https://colab.research.google.com/github/MrudulaBharadwaj/Internship/blob/master/in1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
x=2
x*7


14

In [0]:
x="hello,i'm"
x+"python!"

"hello,i'mpython!"

In [0]:
x=3
type(x)

int

In [0]:
x=chaitra
type(x)


NameError: ignored

In [0]:
x='3'
type(x)


str

In [0]:
type(1)

int

In [0]:
type("hello")

str

In [0]:
type(none)

NameError: ignored

In [0]:
type(None)

NoneType

In [0]:
type(int)

type

In [0]:
type(type)

type

In [0]:
3.0

3.0

In [0]:
3.0
type(3.0)


float

In [0]:
1+1

2

In [0]:
8-1

7

In [0]:
10*2

20

In [0]:
9/3

3.0

In [0]:
4/2

2.0

In [0]:
9.0/3.0

3.0

In [0]:
9/3
type(9/3)

float

In [0]:
9/3
type(9)
type(3)

int

In [0]:
True

True

In [0]:
False

False

In [0]:
not True

False

In [0]:
True and False

False

In [0]:
True or False

True

In [0]:
2*3!=5

True

In [0]:
s='ARTHUR'
s[2]

'T'

In [0]:
s[-1]

'R'

In [0]:
s[:2]

'AR'

In [0]:
s[1:-1]

'RTHU'

In [0]:
s[1:5:2]

'RH'

In [0]:
s[::-1]

'RUHTRA'

In [0]:
name=input("what is your name?")

what is your name?chai


In [0]:
print("am mrudula.nice to  meet you")

am mrudula.nice to  meet you


In [0]:
type(print)

builtin_function_or_method

In [0]:
print("hi chaithra,this is mrudula")

hi chaithra,this is mrudula


In [0]:
type("hi chaithra,this is mrudula")

str

In [0]:
if the world_is_flat:
    print('dont fall off!')

SyntaxError: ignored

In [0]:
the_world_is_flat="MC"
if the_world_is_flat=="MC":
    print('dont fall of!')

dont fall of!


In [0]:
bool(None)

False

In [0]:
bool(True)

True

In [0]:
bool(0)

False

In [0]:
bool(0.0)

False

In [0]:
bool(1)

True

In [0]:
data=[]
if data:
    process(data)
else:
    print("there's no data!")

there's no data!


looping statements

In [0]:
for item in iterable:
    process(item)

NameError: ignored

Range

In [0]:
range(3)


range(0, 3)

In [0]:
for i in range(0,3):
    print(i)

0
1
2


In [0]:
for i in range(2,12,3):
    print(i)

2
5
8
11


                                            BREAK AND CONTINUE

In [0]:
for n in range(10):
    if n==6:
        break
    print(n,end=',')

0,1,2,3,4,5,

In [0]:
for n in range(4):
      if n==4:
          continue
      print(n,end=',')

0,1,2,3,

In [0]:
for n in range(10):
      if n%2==0:
          print("even" , n)
          continue
      print("odd" , n)

even 0
odd 1
even 2
odd 3
even 4
odd 5
even 6
odd 7
even 8
odd 9


#                                                       FUNCTIONS

syntax: def fun_name(para1,para2):
              value=do_something()
              return value(optional)

In [0]:
#prime number generation:
def is_prime(n):
    for i in range(2,n):
        if n % i==0:
            return False
    return True
  
n=int(input("enter a number"))  
for x in range(2,n):
      if is_prime(x):
          print(x,"is prime")
      else:
        print(x,"is not prime")

enter a number3
2 is prime


sort,multiples of 8 range-500,input->string(string match)

In [0]:
print(list(range(0,500,8)))

[0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 264, 272, 280, 288, 296, 304, 312, 320, 328, 336, 344, 352, 360, 368, 376, 384, 392, 400, 408, 416, 424, 432, 440, 448, 456, 464, 472, 480, 488, 496]


In [0]:
list=[30,10,50,89]
for i in list:
    i=int(i)
list.sort()
print(list)

[10, 30, 50, 89]


In [2]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int64'

In [7]:
a.itemsize

8

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [12]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [13]:
 type(b)

numpy.ndarray

In [26]:
import numpy as np
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [27]:
a.ndim

3

In [28]:
a.itemsize

8

In [29]:
type(a)

numpy.ndarray

In [30]:
a.shape

(2, 3, 4)

In [31]:
import numpy as np
a=np.array([2.1,3,4,6,8])
a

array([2.1, 3. , 4. , 6. , 8. ])

In [32]:
a.dtype

dtype('float64')

In [33]:
import numpy as np
a=np.array([1,2.1,3.1,4.6])
a

array([1. , 2.1, 3.1, 4.6])

In [35]:
import numpy as np
a=np.array(["np","mk","jk"])
a

array(['np', 'mk', 'jk'], dtype='<U2')

In [36]:
a.dtype

dtype('<U2')

In [39]:
import numpy as np
a=np.array([1,2])
a

array([1, 2])

In [43]:
import numpy as np
a=np.array([[1,2,3],
           [4,6,7,8]])
a

array([list([1, 2, 3]), list([4, 6, 7, 8])], dtype=object)

In [46]:
import numpy as np
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
import numpy as np
a=np.zeros((2,3,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [49]:
import numpy as np
a=np.ones((2,3,4))
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Empty (np.empty(2,3) creates an matrix of random values) 

In [50]:
import numpy as np
a=np.empty((2,3,4))
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [52]:
import numpy as np
a=np.empty((2,3))
a

array([[1.78610027e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [54]:
import numpy as np
np.arange(10,30,5)

array([10, 15, 20, 25])

In [55]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

using linspace() function

In [57]:
from numpy import pi
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

  **printing Arrays**

In [59]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [60]:
m=np.arange(12).reshape(1,4,3)
print(m)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]


In [62]:
k=np.arange(24).reshape(2,3,4)
print(k)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [64]:
k=np.arange(10).reshape(10,1)
print(k)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [65]:
from numpy import pi
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [67]:
print(np.arange(5).reshape(1,5))

[[0 1 2 3 4]]


In [0]:
np.set_printoptions(threshold=60)

In [75]:
a=np.array([20,30,40,50])
b=np.arange(4)
b
c=a-b
print(c)

[20 29 38 47]


In [77]:
a=np.array([20,30,40,50])
b=np.arange(4)
a**2
print(a)

[20 30 40 50]


In [78]:
b**2

array([0, 1, 4, 9])

In [79]:
a<40

array([ True,  True, False, False])

"*"-used for element by element multiplication

In [80]:
>>> A = np.array( [[1,1],[0,1]] )
>>> B = np.array( [[2,0],[3,4]] )
A * B    

array([[2, 0],
       [0, 4]])

In [81]:
A@B

array([[5, 4],
       [3, 4]])

In [82]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [86]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [92]:
a=np.ones((2,3),dtype=int)
b=np.random.random((2,3))
b*=3
b

array([[2.21533322, 0.20389484, 1.67581077],
       [0.92119422, 2.32587039, 0.9943772 ]])

In [0]:
a=np.ones((2,3),dtype=int)
b=np.arange(5)
b+=a
b

In [100]:
a=np.ones(3,dtype=np.int32)
b=np.linspace(0,pi,3)
b.dtype.name

'float64'

In [101]:
print(a)

[1 1 1]


In [102]:
print(b)

[0.         1.57079633 3.14159265]


In [103]:
c=a+b
c

array([1.        , 2.57079633, 4.14159265])

In [106]:
a=np.random.random((2,3))
a.sum
a

array([[0.62177345, 0.45449017, 0.12928945],
       [0.30887537, 0.13177463, 0.68246279]])

In [108]:
a.min()


0.1292894490206694

In [109]:
a.max()

0.6824627888250286

  **SPECIFYING AXIS PARAMETER**

In [110]:
#SUM OF EACH COLUMN
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [112]:
#SUM OF EACH ROW
b.sum(axis=1)

array([ 6, 22, 38])

In [113]:
#MIN OF EACH ROW
b.min(axis=1)

array([0, 4, 8])

In [114]:
#min of each column
b.min(axis=0)

array([0, 1, 2, 3])

In [0]:
#cumulative sum along each row