<a href="https://colab.research.google.com/github/MrudulaBharadwaj/Internship/blob/master/in1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
x=2
x*7


14

In [0]:
x="hello,i'm"
x+"python!"

"hello,i'mpython!"

In [0]:
x=3
type(x)

int

In [0]:
x=chaitra
type(x)


NameError: ignored

In [0]:
x='3'
type(x)


str

In [0]:
type(1)

int

In [0]:
type("hello")

str

In [0]:
type(none)

NameError: ignored

In [0]:
type(None)

NoneType

In [0]:
type(int)

type

In [0]:
type(type)

type

In [0]:
3.0

3.0

In [0]:
3.0
type(3.0)


float

In [0]:
1+1

2

In [0]:
8-1

7

In [0]:
10*2

20

In [0]:
9/3

3.0

In [0]:
4/2

2.0

In [0]:
9.0/3.0

3.0

In [0]:
9/3
type(9/3)

float

In [0]:
9/3
type(9)
type(3)

int

In [0]:
True

True

In [0]:
False

False

In [0]:
not True

False

In [0]:
True and False

False

In [0]:
True or False

True

In [0]:
2*3!=5

True

In [0]:
s='ARTHUR'
s[2]

'T'

In [0]:
s[-1]

'R'

In [0]:
s[:2]

'AR'

In [0]:
s[1:-1]

'RTHU'

In [0]:
s[1:5:2]

'RH'

In [0]:
s[::-1]

'RUHTRA'

In [0]:
name=input("what is your name?")

what is your name?chai


In [0]:
print("am mrudula.nice to  meet you")

am mrudula.nice to  meet you


In [0]:
type(print)

builtin_function_or_method

In [0]:
print("hi chaithra,this is mrudula")

hi chaithra,this is mrudula


In [0]:
type("hi chaithra,this is mrudula")

str

In [0]:
if the world_is_flat:
    print('dont fall off!')

SyntaxError: ignored

In [0]:
the_world_is_flat="MC"
if the_world_is_flat=="MC":
    print('dont fall of!')

dont fall of!


In [0]:
bool(None)

False

In [0]:
bool(True)

True

In [0]:
bool(0)

False

In [0]:
bool(0.0)

False

In [0]:
bool(1)

True

In [0]:
data=[]
if data:
    process(data)
else:
    print("there's no data!")

there's no data!


looping statements

In [0]:
for item in iterable:
    process(item)

NameError: ignored

Range

In [0]:
range(3)


range(0, 3)

In [0]:
for i in range(0,3):
    print(i)

0
1
2


In [0]:
for i in range(2,12,3):
    print(i)

2
5
8
11


                                            BREAK AND CONTINUE

In [0]:
for n in range(10):
    if n==6:
        break
    print(n,end=',')

0,1,2,3,4,5,

In [0]:
for n in range(4):
      if n==4:
          continue
      print(n,end=',')

0,1,2,3,

In [0]:
for n in range(10):
      if n%2==0:
          print("even" , n)
          continue
      print("odd" , n)

even 0
odd 1
even 2
odd 3
even 4
odd 5
even 6
odd 7
even 8
odd 9


#                                                       FUNCTIONS

syntax: def fun_name(para1,para2):
              value=do_something()
              return value(optional)

In [0]:
#prime number generation:
def is_prime(n):
    for i in range(2,n):
        if n % i==0:
            return False
    return True
  
n=int(input("enter a number"))  
for x in range(2,n):
      if is_prime(x):
          print(x,"is prime")
      else:
        print(x,"is not prime")

enter a number3
2 is prime


sort,multiples of 8 range-500,input->string(string match)

In [0]:
print(list(range(0,500,8)))

[0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 264, 272, 280, 288, 296, 304, 312, 320, 328, 336, 344, 352, 360, 368, 376, 384, 392, 400, 408, 416, 424, 432, 440, 448, 456, 464, 472, 480, 488, 496]


In [0]:
list=[30,10,50,89]
for i in list:
    i=int(i)
list.sort()
print(list)

[10, 30, 50, 89]


In [0]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
a.shape

(3, 5)

In [0]:
a.ndim

2

In [0]:
a.dtype.name

'int64'

In [0]:
a.itemsize

8

In [0]:
a.size

15

In [0]:
type(a)

numpy.ndarray

In [0]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [0]:
 type(b)

numpy.ndarray

In [0]:
import numpy as np
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [0]:
a.ndim

3

In [0]:
a.itemsize

8

In [0]:
type(a)

numpy.ndarray

In [0]:
a.shape

(2, 3, 4)

In [0]:
import numpy as np
a=np.array([2.1,3,4,6,8])
a

array([2.1, 3. , 4. , 6. , 8. ])

In [0]:
a.dtype

dtype('float64')

In [0]:
import numpy as np
a=np.array([1,2.1,3.1,4.6])
a

array([1. , 2.1, 3.1, 4.6])

In [0]:
import numpy as np
a=np.array(["np","mk","jk"])
a

array(['np', 'mk', 'jk'], dtype='<U2')

In [0]:
a.dtype

dtype('<U2')

In [0]:
import numpy as np
a=np.array([1,2])
a

array([1, 2])

In [0]:
import numpy as np
a=np.array([[1,2,3],
           [4,6,7,8]])
a

array([list([1, 2, 3]), list([4, 6, 7, 8])], dtype=object)

In [0]:
import numpy as np
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
import numpy as np
a=np.zeros((2,3,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [0]:
import numpy as np
a=np.ones((2,3,4))
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Empty (np.empty(2,3) creates an matrix of random values) 

In [0]:
import numpy as np
a=np.empty((2,3,4))
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [0]:
import numpy as np
a=np.empty((2,3))
a

array([[1.78610027e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [0]:
import numpy as np
np.arange(10,30,5)

array([10, 15, 20, 25])

In [0]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

using linspace() function

In [0]:
from numpy import pi
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

  **printing Arrays**

In [0]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [0]:
m=np.arange(12).reshape(1,4,3)
print(m)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]


In [0]:
k=np.arange(24).reshape(2,3,4)
print(k)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [0]:
k=np.arange(10).reshape(10,1)
print(k)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [0]:
from numpy import pi
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [0]:
print(np.arange(5).reshape(1,5))

[[0 1 2 3 4]]


In [0]:
np.set_printoptions(threshold=60)

In [0]:
a=np.array([20,30,40,50])
b=np.arange(4)
b
c=a-b
print(c)

[20 29 38 47]


In [0]:
a=np.array([20,30,40,50])
b=np.arange(4)
a**2
print(a)

[20 30 40 50]


In [0]:
b**2

array([0, 1, 4, 9])

In [0]:
a<40

array([ True,  True, False, False])

"*"-used for element by element multiplication

In [0]:
>>> A = np.array( [[1,1],[0,1]] )
>>> B = np.array( [[2,0],[3,4]] )
A * B    

array([[2, 0],
       [0, 4]])

In [0]:
A@B

array([[5, 4],
       [3, 4]])

In [0]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [0]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [0]:
a=np.ones((2,3),dtype=int)
b=np.random.random((2,3))
b*=3
b

array([[2.21533322, 0.20389484, 1.67581077],
       [0.92119422, 2.32587039, 0.9943772 ]])

In [0]:
a=np.ones((2,3),dtype=int)
b=np.arange(5)
b+=a
b

In [0]:
a=np.ones(3,dtype=np.int32)
b=np.linspace(0,pi,3)
b.dtype.name

'float64'

In [0]:
print(a)

[1 1 1]


In [0]:
print(b)

[0.         1.57079633 3.14159265]


In [0]:
c=a+b
c

array([1.        , 2.57079633, 4.14159265])

In [0]:
a=np.random.random((2,3))
a.sum
a

array([[0.62177345, 0.45449017, 0.12928945],
       [0.30887537, 0.13177463, 0.68246279]])

In [0]:
a.min()


0.1292894490206694

In [0]:
a.max()

0.6824627888250286

  **SPECIFYING AXIS PARAMETER**

In [0]:
#SUM OF EACH COLUMN
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [0]:
#SUM OF EACH ROW
b.sum(axis=1)

array([ 6, 22, 38])

In [0]:
#MIN OF EACH ROW
b.min(axis=1)

array([0, 4, 8])

In [0]:
#min of each column
b.min(axis=0)

array([0, 1, 2, 3])

In [0]:
#cumulative sum along each row
import numpy as np
b=np.arange(12).reshape(3,4)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [0]:
#cumulative sum along ecah row
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

**UNIVERSAL FUNCTIONS EXP()_X:e^x,sqrt etc**

In [0]:
B=np.arange(3)
B

array([0, 1, 2])

In [0]:
np.exp(B)#e^0-1,e^1-2.718..,e^2-7.389...

array([1.        , 2.71828183, 7.3890561 ])

In [0]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [0]:
c=np.array([2.,-1.,4.])
np.add(B,c)


array([2., 0., 6.])

In [0]:
c=np.array([2,3,4])
np.add(B,c)

array([2, 4, 6])

In [0]:
np.max(B)

2

In [0]:
np.sort(B)

array([0, 1, 2])

In [0]:
np.all(B)

False

In [0]:
a = np.array([[1, 2], [3, 4]])
np.mean(a)


2.5

**INDEXING ,SLICING ,ITERATING**

In [0]:
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [0]:
a[4]

64

In [0]:
a[10]

IndexError: ignored

In [0]:
a[2:5]

array([ 8, 27, 64])

In [0]:
a[:6:2]

array([ 0,  8, 64])

In [0]:
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [0]:
a[2:4:1]

array([ 8, 27])

In [0]:
a[-1:]

array([729])

In [0]:
a[:-1]

array([  0,   1,   8,  27,  64, 125, 216, 343, 512])

In [0]:
a=np.arange(24).reshape(3,2,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [0]:
a[1:6]

array([[[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [0]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [0]:
a[2]

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

In [0]:
a[1:2]

array([[[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [0]:
a[:2]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [0]:
for i in a:
  print(i**(1/3))

[[0.         1.         1.25992105 1.44224957]
 [1.58740105 1.70997595 1.81712059 1.91293118]]
[[2.         2.08008382 2.15443469 2.22398009]
 [2.28942849 2.35133469 2.41014226 2.46621207]]
[[2.5198421  2.57128159 2.62074139 2.66840165]
 [2.71441762 2.75892418 2.80203933 2.84386698]]


In [0]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [0]:
a[:,0,:0]

array([], shape=(3, 0), dtype=int64)

In [0]:
a[1:,:,:]#selects both rows and columns of 1

array([[[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [0]:
a[2,1,1]

21

In [0]:
a[0:1:2]

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [0]:
a[0,1,3]

7

In [0]:
a[2]

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

In [0]:
a[2:1:1]

array([], shape=(0, 2, 4), dtype=int64)

In [0]:
for row in a:
    print(row)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]]


In [0]:
for column in a:
    print(column)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]]


*** if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array:***

In [0]:
for element in a.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [0]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [0]:
a[1,...]    #same as a[1,:,:]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [0]:
a[...,2]                                   # same as a[:,:,2]

array([[ 2,  6],
       [10, 14],
       [18, 22]])

In [0]:
 #returns element corresponding to index in flattened array
  print(a.flat[5])

5


In [0]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [0]:
a = np.floor(10*np.random.random((3,4)))#generates random numbers in the range specified
a

array([[7., 7., 4., 2.],
       [7., 2., 1., 9.],
       [7., 5., 9., 0.]])

In [0]:
a.ravel()  # returns the array, flattened

array([7., 7., 4., 2., 7., 2., 1., 9., 7., 5., 9., 0.])

In [0]:
a.reshape(6,2) #returns the array with a modified shape

array([[7., 7.],
       [4., 2.],
       [7., 2.],
       [1., 9.],
       [7., 5.],
       [9., 0.]])

In [0]:
a.reshape(3,4)

array([[7., 7., 4., 2.],
       [7., 2., 1., 9.],
       [7., 5., 9., 0.]])

In [0]:
a.T  # returns the array, transposed


array([[7., 7., 7.],
       [7., 2., 5.],
       [4., 1., 9.],
       [2., 9., 0.]])

In [0]:
a.T.shape #returns (columns,rows)

(4, 3)

In [0]:
a.shape#returns (columns,rows)

(3, 4)

**
The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:**

In [0]:
a

array([[7., 7., 4., 2.],
       [7., 2., 1., 9.],
       [7., 5., 9., 0.]])

In [0]:
a.resize((2,6))
a

array([[7., 7., 4., 2., 7., 2.],
       [1., 9., 7., 5., 9., 0.]])

**stacking togther diffeewnt arrays**

In [0]:
 a = np.floor(10*np.random.random((2,2)))
 a

array([[3., 8.],
       [4., 7.]])

In [0]:
b = np.floor(10*np.random.random((2,2)))
b

array([[3., 4.],
       [6., 6.]])

In [0]:
np.vstack((a,b))

array([[3., 8.],
       [4., 7.],
       [3., 4.],
       [6., 6.]])

In [0]:
np.hstack((a,b))

array([[3., 8., 3., 4.],
       [4., 7., 6., 6.]])

**Splitting one array into several smaller ones**

In [2]:
#Using hsplit, you can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur:
import numpy as np
a = np.floor(10*np.random.random((2,12)))
a

array([[8., 1., 2., 7., 6., 5., 4., 3., 7., 1., 0., 5.],
       [2., 2., 9., 4., 4., 3., 7., 9., 2., 3., 8., 9.]])

In [3]:
np.hsplit(a,3) #split a into 3

[array([[8., 1., 2., 7.],
        [2., 2., 9., 4.]]), array([[6., 5., 4., 3.],
        [4., 3., 7., 9.]]), array([[7., 1., 0., 5.],
        [2., 3., 8., 9.]])]

In [4]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[8., 1., 2.],
        [2., 2., 9.]]), array([[7.],
        [4.]]), array([[6., 5., 4., 3., 7., 1., 0., 5.],
        [4., 3., 7., 9., 2., 3., 8., 9.]])]

In [6]:
a=np.arange(12)
b=a
b is a   #a and b are two names for the same ndarray object

True

In [7]:
b.shape=3,4  #changes the shape of array
a.shape

(3, 4)

**view or shallow copy**

In [8]:
#The view method creates a new array object that looks at the same data.
c=a.view
c is a

False

In [14]:
a.shape

(3, 4)

In [15]:
c=np.arange(12)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
c.shape=2,6
a.shape


(3, 4)

In [20]:
c[0,4]=1234
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**linear algebra**

In [21]:
import numpy as np
a=np.array([[1.0, 2.0], [3.0, 4.0]])
a

array([[1., 2.],
       [3., 4.]])

In [23]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [24]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [25]:
u=np.eye(2)   # unit 2x2 matrix; "eye" represents "I"
u

array([[1., 0.],
       [0., 1.]])

In [26]:
j=np.array([[0.0, -1.0], [1.0, 0.0]])
j

array([[ 0., -1.],
       [ 1.,  0.]])

In [27]:
j@j #matrix product

array([[-1.,  0.],
       [ 0., -1.]])

In [29]:
a

array([[1., 2.],
       [3., 4.]])

In [30]:
np.trace(u) #returns the sum of the diagonals

2.0

In [31]:
np.trace(a)

5.0

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.trace(np.eye(2))

2.0

In [34]:
a=np.arange(8).reshape((2,2,2))
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
np.trace(a)

array([6, 8])

In [39]:
a=np.array([[1.0, 2.0], [3.0, 4.0]])
a

array([[1., 2.],
       [3., 4.]])

In [40]:
y = np.array([[5.], [7.]])
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [43]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x=np.linalg.solve(a,b)
x

array([2., 3.])

In [44]:
#check the solution is correct
np.allclose(np.dot(a, x), b)

True

In [0]:
#ARRAYS IN PHYTON IMPORT THE ARRAY MODULE(FROM ARRAY IMPORT)
#ARRAY DECLARATION:(ARRAYIDENTIFIERNAME=ARRAY(TYPECODE,[INITIALIZERS]))

In the declaration above, "arrayIdentifierName" is the name of array, ‘typecode’ lets python know the type of array and ‘Initializers’ are the values with which array is initialized.

In [0]:
my_array = array('i',[1,2,3,4]) #I REPRESENTS THE TYPECODE

In [48]:
from array import *
my_array=array('i',[1,2,3,4])
for i in my_array:
    print(i)

1
2
3
4


2. Access individual elements through indexes

In [50]:
my_array[1]

2

3. Append any value to the array using append() method

In [51]:
my_array.append(10)
my_array

array('i', [1, 2, 3, 4, 10])

4. Insert value in an array using insert() method

In [52]:
my_array.insert(0,0)
my_array                   #value 0 is inserted at at index 0

array('i', [0, 1, 2, 3, 4, 10])

In [53]:
my_array.insert(2,6)
my_array

array('i', [0, 1, 6, 2, 3, 4, 10])

5. Extend python array using extend() method

In [55]:
my_extnd_array=array('i',[7,8,9,10])
my_array.extend(my_extnd_array)
my_array

array('i', [0, 1, 6, 2, 3, 4, 10, 7, 8, 9, 10])

6. Add items from list into array using fromlist() method

In [56]:
c=[11,12,13]
my_array.fromlist(c)
my_array

array('i', [0, 1, 6, 2, 3, 4, 10, 7, 8, 9, 10, 11, 12, 13])

7. Remove any array element using remove() method

In [59]:
my_array.remove(my_array[2])
my_array

array('i', [0, 1, 3, 4, 10, 7, 8, 9, 10, 11, 12, 13])

8. Remove last array element using pop() method

In [60]:
my_array.pop()

13

9. Fetch any element through its index using index() method

In [61]:
my_array.index(2)

ValueError: ignored

In [62]:
my_array

array('i', [0, 1, 3, 4, 10, 7, 8, 9, 10, 11, 12])

In [65]:
my_array.index(5)

ValueError: ignored

10. Reverse a python array using reverse() method

In [66]:
my_array.reverse()
my_array

array('i', [12, 11, 10, 9, 8, 7, 10, 4, 3, 1, 0])

11. Get array buffer information through buffer_info() method
This method provides you the array buffer start address in memory and number of elements in array.

In [67]:
my_array.buffer_info()

(140245841782520, 11)

12. Check for number of occurrences of an element using count() method

In [68]:
my_array.count(9)

1

13. Convert array to string using tostring() method

In [70]:
 my_char_array = array('b', [ord('g'),ord('e'),ord('e'),ord('k')])
 my_char_array

array('b', [103, 101, 101, 107])

14. Convert array to a python list with same elements using tolist() method

In [71]:
c = my_array.tolist()
c

[12, 11, 10, 9, 8, 7, 10, 4, 3, 1, 0]

15. Append a string to char array using fromstring() method

In [72]:
my_char_array.fromstring("stuff")
my_char_array

array('b', [103, 101, 101, 107, 115, 116, 117, 102, 102])

                      generation of prime numbers using functions

In [73]:
def is_prime(n):   #function header
    for i in range(2,n):
        if n%i==0:
            return False
    return True
n=input("enter a number:")
for x in range(2,int(n)):
    if is_prime(x):
        print(x,"is prime")
    else:
        print(x,"is not prime")

enter a number:5
2 is prime
3 is prime
4 is not prime


In [83]:
n=int(input("enter a number:"))
if n>1:
    for i in range(2,n):
        if(n%i)==0:
            print(n,"is prime")
        else:
            print(n,"is not prime")

enter a number:5
5 is not prime
5 is not prime
5 is not prime


In [0]:
def evenodd(n):
    for i in range(0,100):
        if n%2==0:
            print(n)
n=int(input("enter the number:"))
for i in range(0,int(n)):
    if evenodd(n):
        continue
    else:
        break

In [102]:
def even_odd(n):
    list 1=[9,7,6,4,3,10,16]
      for i in list 1:
          if n%2==0:
              print(n)
n=int(input("enter the list1")
      while(n<len(list 1))
          continue
      if n>len(list 1):
          break

SyntaxError: ignored