<a href="https://colab.research.google.com/github/MrudulaBharadwaj/Internship/blob/master/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **PANDAS** it can be created from a list or arrays

In [0]:
import numpy as np
import pandas as pd

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])  #series wraps both the series of indicies and values
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
data[1]

0.5

In [6]:
data[1:3]

1    0.50
2    0.75
dtype: float64

**Series as generalized NumPy array**

In [11]:
data = pd.Series([1, 2, 3, 4],
                 index=['a', 'b', 'c', 'd'])
data

a    1
b    2
c    3
d    4
dtype: int64

In [9]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [13]:
data['b']

2

In [14]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64


Series as specialized dictionary

In [15]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [17]:
population['California']

38332521

In [18]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

Constructing Series objects

In [23]:
#pd.Series(data, index=index)
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [26]:
pd.Series(5,index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [28]:
pd.Series({2:'a',1:'b',3:'c'})

2    a
1    b
3    c
dtype: object

In [30]:
pd.Series({2:'a',1:'b',3:'c'},index=[3,2])

3    c
2    a
dtype: object

In [31]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [32]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [33]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [34]:
states.columns

Index(['population', 'area'], dtype='object')

In [35]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [36]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [37]:
#from a list of dicts
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [38]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

From a two-dimensional NumPy array

In [40]:
pd.DataFrame(np.random.rand(3,2),columns=["foo","bar"],index=['a','b','c'])

foo       bar
a  0.151630  0.281587
b  0.273506  0.613273
c  0.393754  0.893126

In [43]:
#From a NumPy structured array
A = np.zeros(3, dtype=[('A', 'i4'), ('B', 'i4')])
A

array([(0, 0), (0, 0), (0, 0)], dtype=[('A', '<i4'), ('B', '<i4')])

In [44]:
pd.DataFrame(A)

A  B
0  0  0
1  0  0
2  0  0

**The Pandas Index Object***

In [45]:
ind=pd.Index([2,3,5,6,7])
ind

Int64Index([2, 3, 5, 6, 7], dtype='int64')

In [46]:
ind[1]

3

In [47]:
ind[::2]

Int64Index([2, 5, 7], dtype='int64')

In [48]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [49]:
#index doesnot support mutable operations
ind[1]=0

TypeError: ignored

Index as ordered set

In [0]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [51]:
indA & indB  # intersection

Int64Index([3, 5, 7], dtype='int64')

In [52]:
indA|indB #union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [53]:
indA^indB #symmetric difference

Int64Index([1, 2, 9, 11], dtype='int64')

In [54]:
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

# **Data selection and indexing**

In [55]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [56]:
'a' in data

True

In [57]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [58]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [60]:
data['e']=1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

Series as one-dimensional array

In [61]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [62]:

# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [63]:
#masking
data[(data>0.3)&(data<0.8)]

b    0.50
c    0.75
dtype: float64

In [64]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

## Indexers: loc, iloc, and ix

In [65]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [66]:
# explicit index when indexing
data[1]

'a'

In [67]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [68]:
#First, the loc attribute allows indexing and slicing that always references the explicit index:
data.loc[1]

'a'

In [69]:
data.loc[1:3]

1    a
3    b
dtype: object

In [70]:
#The iloc attribute allows indexing and slicing that always references the implicit Python-style index:
data.iloc[1]

'b'

In [72]:
data.iloc[1:3]

3    b
5    c
dtype: object

## Data Selection in DataFrame

In [73]:
#DataFrame as a dictionary
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [74]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [75]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [76]:
data.area is data['area']

True

In [77]:
data.pop is data['pop']

False

In [78]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

DataFrame as two-dimensional array

In [79]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [80]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [81]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [82]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [83]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [84]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [85]:
data.ix[:3, :'pop']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [86]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

# Ufuncs: Index Preservation

In [87]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [88]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [89]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [90]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

UFuncs: Index Alignment

In [0]:
#Index alignment in Series
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [92]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [93]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [94]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [95]:
A.add(B, fill_value=0)  #same as A+B

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

Index alignment in DataFrame

In [96]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [98]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('ABC'))
B

A  B  C
0  3  8  2
1  4  2  6
2  4  8  6

In [99]:
A + B

A     B   C
0  4.0  19.0 NaN
1  9.0   3.0 NaN
2  NaN   NaN NaN

In [100]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0  4.0  19.0   6.5
1  9.0   3.0  10.5
2  8.5  12.5  10.5

## Ufuncs: Operations Between DataFrame and Series

In [101]:
A = rng.randint(10, size=(3, 4))
A

array([[1, 3, 8, 1],
       [9, 8, 9, 4],
       [1, 3, 6, 7]])

In [102]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 8,  5,  1,  3],
       [ 0,  0, -2,  6]])

In [103]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  8  5  1  3
2  0  0 -2  6

In [104]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -2  0  5 -2
1  1  0  1 -4
2 -2  0  3  4

In [105]:
halfrow = df.iloc[0, ::2]
halfrow

Q    1
S    8
Name: 0, dtype: int64

In [106]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  8.0 NaN  1.0 NaN
2  0.0 NaN -2.0 NaN

In [107]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)